// Monuments v7 — clean rebuild. No legacy monument overrides are used.
state.monumentView = 'list';
state.monumentSelected = null;
state.monumentFilter = 'all';

const MONUMENT_ASSETS = {
  fuseClose: 'https://www.playrust.nl/wp-content/uploads/2018/06/fusebox.jpg',
  greenReader: 'https://gamerempire.net/wp-content/uploads/2023/05/Rust-Where-to-Get-and-Use-a-Green-Keycard.jpg',
  domeCurrent: 'https://staticg.sportskeeda.com/editor/2025/10/704e9-17595468595192-1920.jpg?w=1200',
  green: 'https://files.facepunch.com/rust/item/keycard_green_512.png',
  blue: 'https://files.facepunch.com/rust/item/keycard_blue_512.png',
  red: 'https://files.facepunch.com/rust/item/keycard_red_512.png',
  fuse: 'https://files.facepunch.com/rust/item/fuse_512.png'
};

const MONUMENTS_V7 = [
  {id:'outpost',name:'Outpost',group:'safe',icon:'🛒',need:'Safe Zone',reward:'Recycler • Vending • Workbenches',note:'PvP yok. Ticaret ve recycle merkezi.',image:'',steps:[{title:'Safe Zone’a gir',text:'Hostile timer yoksa güvenle içeri gir.',type:'move'},{title:'Recycler / Vending',text:'Component recycle et, NPC vendinglerden alışveriş yap.',type:'loot'}]},
  {id:'bandit',name:'Bandit Camp',group:'safe',icon:'🎰',need:'Safe Zone',reward:'Gambling • AirWolf • Recycler',note:'Gambling ve heli shop için.',image:'',steps:[{title:'Safe Zone’a gir',text:'Hostile değilsen güvenli.',type:'move'},{title:'Gambling / Shops',text:'Scrap ve araç alışverişi.',type:'loot'}]},
  {id:'fishing-village',name:'Fishing Village',group:'safe',icon:'🎣',need:'Safe Zone',reward:'Boat • Missions',note:'Boat ve fishing görevleri.',image:'',steps:[{title:'Dock',text:'Kıyıdaki safe zone’a yanaş.',type:'move'},{title:'Boat / Mission',text:'Boat al veya fishing mission başlat.',type:'loot'}]},
  {id:'apartment',name:'Apartment Complex',group:'safe',icon:'🏢',need:'Scrap ile oda kirala',reward:'Room rental • Shops',note:'Temmuz 2026’da eklendi; kart/fuse puzzle değil.',image:'https://files.facepunch.com/paddy/20260702/apartment_complex_1.jpg',steps:[{title:'Lobby',text:'Receptionist ile konuş.',type:'move'},{title:'Room seç',text:'Scrap bütçene göre oda kirala.',type:'loot'}]},
  {id:'cabins',name:'Abandoned Cabins',group:'source',icon:'🟩',need:'Kart gerekmez',reward:'Green Card',note:'Green Card başlangıç noktası.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Abandoned-Cabins-Monument-and-Green-Keycard-Location-RUST-1920x1052.jpeg',steps:[{title:'Sarı 2 katlı binaya gir',text:'Ana loot binasını bul.',type:'move'},{title:'Üst kata çık',text:'İç merdivenleri kullan.',type:'climb'},{title:'Green Card’ı al',text:'Köşe masadaki Green Card spawnını kontrol et.',type:'green'}]},
  {id:'lighthouse',name:'Lighthouse',group:'source',icon:'🟩',need:'Kart gerekmez',reward:'Green Card',note:'Kolay erken wipe Green Card.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Lighthouse-Monument-and-Green-Keycard-Location-RUST.jpeg-1920x1026.jpeg',steps:[{title:'Lighthouse içine gir',text:'Alt kapıdan gir.',type:'move'},{title:'Yukarı çık',text:'Merdivenlerle üst bölüme çık.',type:'climb'},{title:'Green Card',text:'Üst odadaki masayı kontrol et.',type:'green'}]},
  {id:'supermarket',name:'Abandoned Supermarket',group:'source',icon:'🟩',need:'Kart gerekmez',reward:'Green Card',note:'Ofis odasındaki masa.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Supermarket-Monument-and-Green-Keycard-Location-RUST-1920x1069.jpeg',steps:[{title:'Ana binaya gir',text:'Market içine gir.',type:'move'},{title:'Ofis odasını bul',text:'Küçük arka/yan odayı kontrol et.',type:'move'},{title:'Green Card',text:'Masa üstündeki spawnı al.',type:'green'}]},
  {id:'gas',name:"Oxum's Gas Station",group:'source',icon:'🟩',need:'Kart gerekmez',reward:'Green Card',note:'Masa üzerindeki Green Card spawnı.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Gas-Station-Monument-and-Green-Keycard-Location-RUST-1920x1044.jpeg',steps:[{title:'Ana binaya gir',text:'Ön veya arka giriş.',type:'move'},{title:'Orta/ofis odayı bul',text:'Merkez masa bölümüne geç.',type:'move'},{title:'Green Card',text:'Masa üstünü kontrol et.',type:'green'}]},
  {id:'junkyard',name:'Junkyard',group:'source',icon:'🟩',need:'Kart gerekmez',reward:'Green Card',note:'Köprü/container tarafında.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Junkyard-Monument-and-Green-Keycard-Location-RUST-1899x1080.jpeg',steps:[{title:'Merkez köprüye git',text:'Monument ortasını bul.',type:'move'},{title:'Üste çık',text:'Köprü/container seviyesine çık.',type:'climb'},{title:'Green Card',text:'Container içindeki masayı kontrol et.',type:'green'}]},
  {id:'dome',name:'The Dome',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'Fuse → switch → Green reader → Blue Card.',image:'https://itemlevel.net/wp-content/uploads/2023/05/The-Dome-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1050.jpeg',video:{id:null},steps:[{title:'Fuse shack’i bul',text:'Normal Dome climb rotasının yanındaki metal shack.',type:'move',image:MONUMENT_ASSETS.domeCurrent},{title:'Fuse tak',text:'Shack içindeki fuse box’a 1 Electric Fuse tak.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Switch’i aç',text:'Shack dışındaki power switch’i aktif et.',type:'switch',image:MONUMENT_ASSETS.domeCurrent},{title:'İkinci shack’e koş',text:'Fuel tankları tarafındaki puzzle shack’e git.',type:'move',image:'https://itemlevel.net/wp-content/uploads/2023/05/The-Dome-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1050.jpeg'},{title:'Green Card bas',text:'Green reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card’ı al',text:'Puzzle room içindeki Blue Card ve loot’u al.',type:'blue',image:'https://itemlevel.net/wp-content/uploads/2023/05/The-Dome-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1050.jpeg'}]},
  {id:'ferry',name:'Ferry Terminal',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'Metal shack power → karşı shack Green door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Ferry-Terminal-Monument-and-Blue-Keycard-Location-RUST-1891x1080.jpeg',steps:[{title:'Power shack’i bul',text:'Terminalin sol tarafındaki metal shack.',type:'move'},{title:'Fuse tak',text:'Fuse box’a 1 Electric Fuse tak.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Switch’i aç',text:'Shack arkasındaki switch’i aktif et.',type:'switch'},{title:'Karşı shack’e git',text:'Monumentin karşı kenarındaki card room.',type:'move'},{title:'Green Card bas',text:'Reader’dan içeri gir.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card',text:'İçerideki Blue Card ve crate’leri al.',type:'blue'}]},
  {id:'small-harbor',name:'Small Harbor',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'2 katlı bina → fuse/switch → üst kat Green door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Small-Harbor-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1064.jpeg',steps:[{title:'2 katlı binayı bul',text:'Subway girişinin önündeki puzzle binası.',type:'move'},{title:'Fuse + Switch',text:'1. katta fuse tak ve yanındaki switch’i aç.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Üst kata çık',text:'Merdivenden 2. kata çık.',type:'climb'},{title:'Green Card bas',text:'Üst kattaki reader’ı kullan.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card',text:'İçerideki Blue Card’ı al.',type:'blue'}]},
  {id:'large-harbor',name:'Large Harbor',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'D2 power → H2 Green room.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Large-Harbor-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1888x1080.jpeg',steps:[{title:'Power container/shack',text:'Shipping building yakınındaki fuse noktasını bul.',type:'move'},{title:'Fuse tak + switch',text:'Fuse tak ve dış switch’i aç.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'H2 / puzzle container',text:'Red hangar altındaki card room’a git.',type:'move'},{title:'Green Card bas',text:'Green reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card',text:'Blue Card ve crate’leri al.',type:'blue'}]},
  {id:'satellite',name:'Satellite Dish',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'Container power → karşı container Green door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Satellite-Dish-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1064.jpeg',steps:[{title:'Power container',text:'Monument kenarındaki fuse containerını bul.',type:'move'},{title:'Fuse tak',text:'Fuse box’a Electric Fuse tak.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Switch’i aç',text:'Container arkasındaki switch’i aç.',type:'switch'},{title:'Green room’a git',text:'Karşı taraftaki card containerına koş.',type:'move'},{title:'Green Card',text:'Reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card',text:'Masa üstündeki Blue Card’ı al.',type:'blue'}]},
  {id:'sewer',name:'Sewer Branch',group:'green',icon:'🟢',need:'Green Card + 1 Fuse',reward:'Blue Card',note:'Recycler binası → pipe → Green door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Sewer-Branch-Monument-Green-Keycard-and-Blue-Keycard-Location-RUST-1920x1075.jpeg',steps:[{title:'Recycler binasını bul',text:'Recycler yanındaki power binasına gir.',type:'move'},{title:'Fuse + Switch',text:'Fuse tak ve switch’i aç.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Büyük pipe’a gir',text:'Dışarı çıkıp büyük pipe/tünel rotasına gir.',type:'tunnel'},{title:'Green Card door',text:'Pipe sonundaki reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'İçeri devam et',text:'İlk roomdan sonraki chamber’a ilerle.',type:'move'},{title:'Blue Card',text:'Masa üstündeki Blue Card’ı al.',type:'blue'}]},
  {id:'radtown',name:'Radtown',group:'green',icon:'🟢',need:'Green Card + 1 Fuse + Rad Gear',reward:'Blue Card',note:'Garage power → üst oda Green door.',image:'https://files.facepunch.com/paddy/20240928/rust_worldUpdate_radtown_22.jpg',steps:[{title:'Garage binasını bul',text:'Radtown garage bölümüne git.',type:'move'},{title:'Fuse tak',text:'Binanın sol dış tarafındaki fuse box.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Switch’i aç',text:'Power switch’i aktif et.',type:'switch'},{title:'Üst odaya çık',text:'Merdivenlerle yukarı.',type:'climb'},{title:'Green Card',text:'Sağ taraftaki reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Blue Card',text:'İçerideki table loot’u al.',type:'blue'}]},
  {id:'water',name:'Water Treatment Plant',group:'blue',icon:'🔵',need:'Blue Card + 1 Fuse',reward:'Red Card',note:'Gate building power → roof Blue door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Water-Treatment-Plant-Monument-Blue-Keycard-Fragments-and-Red-Keycard-Location-RUST-1920x1057.jpeg',steps:[{title:'Gate binasını bul',text:'Ortası geçişli büyük gate building.',type:'move'},{title:'Üst kata çık',text:'Gate wheel bölümünden yukarı.',type:'climb'},{title:'Fuse tak',text:'Üst kattaki fuse box’a 1 fuse.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Timer / switch',text:'Fuse yanındaki timer switch’i başlat.',type:'switch'},{title:'Köşe binaya koş',text:'Çıkıp puzzle roof binasına git.',type:'move'},{title:'Çatıya çık',text:'Dış ladder ile roof level.',type:'climb'},{title:'Blue Card bas',text:'Çatı kapısındaki Blue reader.',type:'blue'},{title:'Red Card',text:'İçeride Red Card ve loot.',type:'red'}]},
  {id:'power',name:'Power Plant',group:'blue',icon:'🔵',need:'Green + Blue Card + 1 Fuse',reward:'Red Card',note:'Switch chain → Green room → Fuse → Blue room.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Power-Plant-Monument-Blue-Keycard-Fragments-and-Red-Keycard-Location-RUST-1920x1062.jpeg',steps:[{title:'Switch #1',text:'Köşe üç katlı binada, merdiven altı switch.',type:'switch',image:'https://files.facepunch.com/martynchapman/2026/August/rust_powerfuses_4_1080_jpg.jpg'},{title:'Switch #2 + timer',text:'Slanted roof / karşı binadaki ikinci power aşaması.',type:'switch'},{title:'Green Card room',text:'Central building Green reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'İç switch',text:'Green room içindeki ek switch’i aç.',type:'switch'},{title:'Üst kata çık',text:'Blue room seviyesine çık.',type:'climb'},{title:'Fuse tak',text:'Blue room yakınındaki fuse box.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Blue Card',text:'Blue reader’dan final loot room’a gir.',type:'blue'},{title:'Red Card',text:'İçerideki Red Card’ı al.',type:'red'}]},
  {id:'airfield',name:'Airfield',group:'blue',icon:'🔵',need:'Green + Blue Card + 2 Fuse + Hazmat',reward:'Red Card',note:'Main building power → pipe tunnel → 2nd fuse → Blue door.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Airfield-Monument-Blue-Keycard-Fragments-and-Red-Keycard-Location-RUST-1920x1080.jpeg',steps:[{title:'Main building’e gir',text:'Sol taraftaki kapıdan girip köşe odaya dön.',type:'move',image:'https://files.facepunch.com/kaantasan/1b0511b1/Aug2026_player_maintained_Monuments_Airfield_Terminals_2_4K.jpg'},{title:'Fuse #1',text:'Küçük köşe odada ilk fuse.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Switch #1',text:'Fuse #1 yanında switch’i aç.',type:'switch'},{title:'Pipe tunnel',text:'Dışarı çık → brick fence → pipe içine gir.',type:'tunnel'},{title:'Green Card',text:'Underground Green reader’dan geç.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'Fuse #2',text:'Green bölüm sonrası ikinci fuse.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Blue Card',text:'Final underground Blue reader.',type:'blue'},{title:'Red Card',text:'Final loot roomdan Red Card.',type:'red'}]},
  {id:'trainyard',name:'Train Yard',group:'blue',icon:'🔵',need:'Blue Card + 1 Fuse',reward:'Red Card',note:'Current 2026 red-card route: switch chain → fuse → Blue room.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Trainyard-Monument-Blue-Keycard-Fragments-and-Red-Keycard-Location-RUST-1920x1024.jpeg',steps:[{title:'İlk power switch',text:'Recycler/generator tarafındaki landmarktan başla.',type:'switch'},{title:'İkinci switch',text:'Karşı taraftaki ikinci power aşamasını aç.',type:'switch'},{title:'Central building',text:'Ana puzzle binasına gir.',type:'move'},{title:'Fuse tak',text:'Central building fuse box.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Blue Card',text:'Final Blue reader ile loot room’u aç.',type:'blue'},{title:'Red Card',text:'Red Card ve loot’u al.',type:'red'}]},
  {id:'arctic',name:'Arctic Research Base',group:'blue',icon:'🔵',need:'Blue Card + Combat Gear',reward:'Red Card',note:'Scientist clear → Blue door/container → Red Card.',image:'https://itemlevel.net/wp-content/uploads/2023/05/Arctic-Research-Base-Monument-Blue-Keycard-Fragments-and-Red-Keycard-Location-RUST-1920x1056.jpeg',steps:[{title:'Scientistleri temizle',text:'Orta compounddaki scientistleri temizle.',type:'combat'},{title:'Red containerları bul',text:'Ortadaki iki büyük kırmızı container.',type:'move'},{title:'Blue reader',text:'Loot container kapısında Blue Card kullan.',type:'blue'},{title:'Red Card',text:'İçeride Red Card ve loot.',type:'red'}]},
  {id:'military-tunnels',name:'Military Tunnels',group:'endgame',icon:'🪖',need:'Green + Blue + Red Card + Fuse(s) + Hazmat',reward:'Elite Loot',note:'Multi-stage underground puzzle + heavy scientists.',image:'https://www.rustbench.com/wiki/Monuments/military-tunnels/20260517164058_1.jpg',video:{id:'E3wZOGM3RS4',start:320},steps:[{title:'Armory route',text:'Front entrance → sağ → Armory koridoru.',type:'move',clip:320},{title:'Fuse / timer',text:'Fuse box ve timer aşamasını başlat.',type:'fuse',image:MONUMENT_ASSETS.fuseClose,clip:330},{title:'Green stage',text:'Storage Green reader’dan geç ve iç switch’i aç.',type:'green',image:MONUMENT_ASSETS.greenReader,clip:350},{title:'Blue stage',text:'Blue door/timer aşamasına ilerle.',type:'blue',clip:380},{title:'Red stage',text:'Red reader ile elite loot bölümünü aç.',type:'red',clip:400},{title:'Exit',text:'Spiral staircase / exit button rotasını kullan.',type:'move',clip:420}]},
  {id:'launch',name:'Launch Site',group:'endgame',icon:'🚀',need:'Green + Red Card + 2 Fuse + Hazmat',reward:'Elite Loot • Bradley',note:'Blue Card gerekmez. Green → Fuse → Red progression.',image:'https://files.facepunch.com/paddy/20220302/launchsite2.jpg',steps:[{title:'Perimetre',text:'Full rad gear ile yaklaş; scientist/Bradley kontrolü yap.',type:'combat'},{title:'Fuse #1',text:'İlk puzzle fuse aşamasını aktif et.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Green Card',text:'İlk gated puzzle bölümüne Green Card ile gir.',type:'green',image:MONUMENT_ASSETS.greenReader},{title:'İç bina rotası',text:'Scientistli ana building/corridor rotasını geç.',type:'move'},{title:'Fuse #2',text:'Final power aşamasına ikinci fuse’u tak.',type:'fuse',image:MONUMENT_ASSETS.fuseClose},{title:'Red Card',text:'Final reader’da Red Card kullan.',type:'red'},{title:'Elite Loot',text:'Control room / elite loot’u al.',type:'loot'}]},
  {id:'missile',name:'Missile Silo',group:'endgame',icon:'☢️',need:'Red Card + 1 Fuse + Hazmat',reward:'Elite Loot',note:'Dikey 5 katlı ağır PvE.',image:'https://www.rustbench.com/wiki/Monuments/missile-silo/20260517164131_1.jpg',video:{id:'8G_JnajHAnc',start:0},steps:[{title:'Surface clear',text:'Giriş çevresindeki scientistleri temizle.',type:'combat',clip:0},{title:'Fuse / elevator power',text:'Elevator/power aşamasında fuse kullan.',type:'fuse',image:MONUMENT_ASSETS.fuseClose,clip:35},{title:'Red Card',text:'Red reader ile descent/final access aç.',type:'red',clip:65},{title:'Kat kat in',text:'NVG scientistleri temizleyerek aşağı ilerle.',type:'combat',clip:90},{title:'Elite Loot',text:'Final loot ve silo chamber bölgesi.',type:'loot',clip:140}]},
  {id:'small-oil',name:'Small Oil Rig',group:'endgame',icon:'🛢️',need:'Cards/Fuse + Combat Gear',reward:'Locked Crate • Military Loot',note:'Dikey offshore monument.',image:'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/ss_08a111660a92c33c10d62e74620d258c216fd0bb.1920x1080.jpg',video:{id:'2lzGW8X5NcY',start:0},steps:[{title:'Dock',text:'Boat ile alt platformdan yanaş.',type:'move'},{title:'Lower clear',text:'Alt/orta kat scientistleri temizle.',type:'combat'},{title:'Card/Fuse room',text:'Puzzle room kart/fuse aşamasını aç.',type:'fuse'},{title:'Upper floors',text:'Üst kat loot ve card roomları temizle.',type:'move'},{title:'Locked Crate',text:'Event crate için üstte pozisyon al.',type:'loot'}]},
  {id:'large-oil',name:'Large Oil Rig',group:'endgame',icon:'🛢️',need:'Cards/Fuse + Heavy Combat',reward:'Locked Crate • Elite Loot',note:'Small Rig’den daha büyük ve daha yoğun.',image:'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/ss_651097c65458ae555b42c42dd9667d7174397bdf.1920x1080.jpg',video:{id:'GN4khDsR6z4',start:0},steps:[{title:'Dock',text:'Alt platformdan yanaş.',type:'move'},{title:'Level clear',text:'Kat kat scientist temizle.',type:'combat'},{title:'Puzzle rooms',text:'Kart/fuse odalarını sırayla aç.',type:'fuse'},{title:'Red / high-tier rooms',text:'Üst kat yüksek seviye loot alanlarına geç.',type:'red'},{title:'Locked Crate',text:'Heavy Scientist event için üstte tutun.',type:'loot'}]},
  {id:'labs',name:'Underwater Labs',group:'endgame',icon:'🌊',need:'Diving/Sub + Layouta göre Cards/Fuse',reward:'Lab Loot',note:'Procedural layout; sabit rota yok.',image:'https://i.ytimg.com/vi/Yj38XRHpD_o/maxresdefault.jpg',video:{id:'Yj38XRHpD_o',start:0},steps:[{title:'Moonpool entry',text:'Sub/boat ile uygun moonpool girişini bul.',type:'move'},{title:'Layout scan',text:'Bu wipe için oluşan modülleri öğren.',type:'move'},{title:'Scientist clear',text:'Koridor/room scientistlerini temizle.',type:'combat'},{title:'Keycard rooms',text:'Spawn olan Blue/Red roomları aç.',type:'blue'},{title:'Exit plan',text:'Oksijen ve moonpool çıkışını koru.',type:'move'}]},
  {id:'excavator',name:'Giant Excavator Pit',group:'other',icon:'⛏️',need:'Diesel + Combat',reward:'Bulk Resources',note:'Keycard puzzle değil; diesel ile resource event.',image:'',steps:[{title:'Scientist clear',text:'Excavator çevresini temizle.',type:'combat'},{title:'Diesel kullan',text:'Control bölümünde diesel ile excavator çalıştır.',type:'fuse'},{title:'Resource seç',text:'İstediğin resource output’u seç.',type:'loot'}]},
  {id:'abandoned-military',name:'Abandoned Military Base',group:'other',icon:'🪖',need:'Combat Gear',reward:'Military Loot',note:'PvE/loot monument; kart progression ana odak değil.',image:'',steps:[{title:'Approach',text:'Cover kullanarak compounda gir.',type:'move'},{title:'Clear',text:'NPC/players için alanı temizle.',type:'combat'},{title:'Loot',text:'Military crate rotasını tamamla.',type:'loot'}]},
  {id:'mining-outpost',name:'Mining Outpost',group:'other',icon:'⛏️',need:'Yok',reward:'Recycler • Basic Loot',note:'Küçük roadside monument.',image:'',steps:[{title:'Loot sweep',text:'Crate ve barrel rotasını dön.',type:'loot'},{title:'Recycler',text:'Componentleri recycle et.',type:'loot'}]},
  {id:'quarry',name:'Quarry',group:'other',icon:'🪨',need:'Fuel / monument tipine göre',reward:'Resources',note:'Resource monument.',image:'',steps:[{title:'Area check',text:'Çevreyi güvene al.',type:'move'},{title:'Operate',text:'Monument mekanizmasına göre çalıştır.',type:'loot'}]}
];

const MONUMENT_GROUPS = [['all','Tümü'],['source','Green Card Kaynakları'],['green','Green Puzzle → Blue'],['blue','Blue Puzzle → Red'],['endgame','Endgame'],['safe','Safe / Utility'],['other','Diğer']];
function m7Src(url){ return url ? `/api/image?url=${encodeURIComponent(url)}` : ''; }
function v7TypeIcon(type){ const map={fuse:MONUMENT_ASSETS.fuse,green:MONUMENT_ASSETS.green,blue:MONUMENT_ASSETS.blue,red:MONUMENT_ASSETS.red}; if(map[type]) return `<img src="${m7Src(map[type])}" alt="">`; const s={move:'⌖',climb:'↟',tunnel:'◉',switch:'⚡',combat:'☠',loot:'✦'}; return `<span>${s[type]||'→'}</span>`; }
function v7MediaForStep(monument, step){ const img=step.image||monument.image; const clipStart=step.clip; const video=monument.video; return `<div class="m7-step-media">${img?`<img src="${m7Src(img)}" alt="${escapeHtml(monument.name)} — ${escapeHtml(step.title)}" loading="lazy">`:`<div class="m7-media-empty">${v7TypeIcon(step.type)}</div>`}${video&&video.id&&clipStart!==undefined?`<button class="m7-clip-btn" type="button" data-m7-video="${video.id}" data-m7-start="${clipStart}">▶ Bu adımı videoda aç</button>`:''}</div>`; }
function m7ListCard(m){ return `<button class="m7-list-card" data-m7-open="${m.id}"><div class="m7-card-media">${m.image?`<img src="${m7Src(m.image)}" alt="${escapeHtml(m.name)}" loading="lazy">`:`<span>${m.icon}</span>`}</div><div class="m7-card-body"><div class="m7-card-title"><h3>${escapeHtml(m.name)}</h3><span>${m.icon}</span></div><strong>${escapeHtml(m.need)}</strong><small>${escapeHtml(m.reward)}</small><p>${escapeHtml(m.note)}</p></div></button>`; }
function monumentsLandingV7(){ const f=state.monumentFilter||'all'; const list=f==='all'?MONUMENTS_V7:MONUMENTS_V7.filter(m=>m.group===f); return `<section class="m7-page"><div class="m7-hero"><div><div class="eyebrow">MONUMENTS</div><h2>Tüm monumentler</h2><p>Karta bas → detaylı rota açılır. Puzzle monumentlerinde Fuse / Switch / Card adımları ayrı ayrı gösterilir.</p></div><div class="m7-chain"><span>🟩 Green</span><b>→</b><span>🟦 Blue</span><b>→</b><span>🟥 Red</span></div></div><div class="m7-filters">${MONUMENT_GROUPS.map(([k,l])=>`<button class="${f===k?'active':''}" data-m7-filter="${k}">${l}</button>`).join('')}</div><div class="m7-grid">${list.map(m7ListCard).join('')}</div></section>`; }
function m7QuickNav(current){ const idx=MONUMENTS_V7.findIndex(m=>m.id===current.id); const prev=MONUMENTS_V7[(idx-1+MONUMENTS_V7.length)%MONUMENTS_V7.length]; const next=MONUMENTS_V7[(idx+1)%MONUMENTS_V7.length]; return `<div class="m7-detail-nav"><button data-m7-back>← Tüm monumentler</button><div class="m7-detail-scroll">${MONUMENTS_V7.map(m=>`<button class="${m.id===current.id?'active':''}" data-m7-open="${m.id}">${escapeHtml(m.name)}</button>`).join('')}</div><div class="m7-prev-next"><button data-m7-open="${prev.id}">← ${escapeHtml(prev.name)}</button><button data-m7-open="${next.id}">${escapeHtml(next.name)} →</button></div></div>`; }
function monumentDetailV7(m){ return `<section class="m7-detail">${m7QuickNav(m)}<div class="m7-detail-head"><div><div class="eyebrow">${m.icon} MONUMENT GUIDE</div><h2>${escapeHtml(m.name)}</h2><p>${escapeHtml(m.note)}</p></div><div class="m7-require"><small>GEREKEN</small><strong>${escapeHtml(m.need)}</strong><span>${escapeHtml(m.reward)}</span></div></div>${m.image?`<div class="m7-overview"><img src="${m7Src(m.image)}" alt="${escapeHtml(m.name)} overview"></div>`:''}<div class="m7-step-head"><span>STEP-BY-STEP</span><h3>${m.steps.length} adım</h3></div><div class="m7-steps">${m.steps.map((s,i)=>`<article class="m7-step" id="m7-step-${i+1}"><div class="m7-step-top"><b>${i+1}</b><div class="m7-step-icon">${v7TypeIcon(s.type)}</div><div><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.text)}</p></div></div>${v7MediaForStep(m,s)}</article>`).join('')}</div>${m.video&&m.video.id?`<div class="m7-full-video"><button type="button" data-m7-video="${m.video.id}" data-m7-start="${m.video.start||0}">▶ Full walkthrough aç</button></div>`:''}${m7QuickNav(m)}</section>`; }
monumentPage=function(){ if(state.monumentView==='detail'&&state.monumentSelected){const m=MONUMENTS_V7.find(x=>x.id===state.monumentSelected);if(m)return monumentDetailV7(m);} return monumentsLandingV7(); };
const shellBeforeM7=shell; shell=function(content){const quick=`<nav class="m7-global-nav"><button data-nav="home">⌂ Home</button><button data-nav="commands">⌘ Console</button><button data-nav="config">⚡ Config</button><button data-nav="monuments" class="${state.page==='monuments'?'active':''}">▦ Monuments</button><button data-nav="raid">💥 Raid</button></nav>`;return shellBeforeM7(content).replace('<div class="layout">',`${quick}<div class="layout">`);};
const bindBeforeM7=bindEvents; bindEvents=function(){bindBeforeM7();document.querySelectorAll('[data-nav="monuments"]').forEach(b=>b.addEventListener('click',()=>{state.monumentView='list';state.monumentSelected=null;render();}));document.querySelectorAll('[data-m7-filter]').forEach(b=>b.addEventListener('click',()=>{state.monumentFilter=b.dataset.m7Filter;state.monumentView='list';render();}));document.querySelectorAll('[data-m7-open]').forEach(b=>b.addEventListener('click',()=>{state.monumentSelected=b.dataset.m7Open;state.monumentView='detail';window.scrollTo({top:0});render();}));document.querySelectorAll('[data-m7-back]').forEach(b=>b.addEventListener('click',()=>{state.monumentView='list';state.monumentSelected=null;window.scrollTo({top:0});render();}));document.querySelectorAll('[data-m7-video]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.m7Video,start=Number(b.dataset.m7Start||0);const wrap=document.createElement('div');wrap.className='m7-video-modal';wrap.innerHTML=`<div class="m7-video-dialog"><button class="m7-video-close">×</button><iframe src="https://www.youtube-nocookie.com/embed/${id}?start=${start}&autoplay=1&rel=0" title="Rust monument video" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>`;document.body.appendChild(wrap);wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.classList.contains('m7-video-close'))wrap.remove();});}));};
render();
